apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: default
      username: default
    secureJsonData:
      password: ${CLICKHOUSE_PASS}
    isDefault: true
    editable: true